[workspace]
authors = ["Cristobal Gallego-Castillo"]
channels = ["conda-forge", "bioconda"]
name = "ISA-NUTS_potentials"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.10"
snakemake = ">=9.7.1"
pandas = ">=2.3"
atlite = ">=0.4"
cartopy = "*"
matplotlib = "*"
ipykernel = "*"
