[workspace]
authors = ["Cristóbal José Gallego Castillo <83344529+cristobal-GC@users.noreply.github.com>"]
channels = ["conda-forge", "bioconda"]
name = "ISA-NUTS_potentials"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.10"
pandas = "*"
snakemake-minimal = ">=9.7.1"
matplotlib = "*"
graphviz = "*"
atlite = ">=0.4.1,<0.5"
