
########## WILDCARDS
regions:
- ES11
- ES111

resources:
- onwind
- solar


formats:
- pdf
- png

resolutions:
- HR
- LR


########## PARAMETERS
map_params:
  LR:
    size: 12
    linewidth: 1.5
    fontsize: 16
  HR:
    size: 36
    linewidth: 4.5
    fontsize: 48
