
########## WILDCARDS
regions:
- ES11
- ES111

resources:
- onwind
#- solar


formats:
- pdf
- png

resolutions:
#- HR
- LR

cutouts:
#- newa
- era5
#- ibera5

years:
#- 2013
- 2023



########## PARAMETERS

cutout_params:
  era5_2023:
    path: "/home/aerolinux4/DOCK_01/SANDBOXES/sandbox_Ryzen3975/cutouts/europe-2023-sarah3-era5.nc"
  ibera5_2023:
    path: "/home/aerolinux4/DOCK_01/SANDBOXES/sandbox_Ryzen3975/cutouts/iberia-2023-era5.nc"

CF_params:
  onwind:
    turbine: Vestas_V112_3MW_h100
    correction_factor:  0.93
  solar:
    panel: CSi
    orientation:
      slope: 35
      azimuth: 180.0
    correction_factor: 0.85


map_params:
  LR:
    size: 12
    linewidth: 1.5
    fontsize: 16
  HR:
    size: 36
    linewidth: 4.5
    fontsize: 48
  cutout:
    onwind:
      cmap: viridis
      units: m/s
    solar:
      cmap: YlOrRd
      units: W/m2
  CF:
    onwind:
      cmap: 'BuPu'



